cmake_minimum_required(VERSION 3.5)

set(SLMDISPLAY_INCLUDE_DIR ${CMAKE_CURRENT_LIST_DIR}/../includes CACHE INTERNAL "")

if(NOT "${CMAKE_GENERATOR_PLATFORM}" MATCHES "(Win64|IA64|x64)")
	set(SLMDISPLAY_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/../lib/win32/lib/holoeye_slmdisplaysdk.lib CACHE INTERNAL "")
else()
	set(SLMDISPLAY_LIBRARY ${CMAKE_CURRENT_LIST_DIR}/../lib/win64/lib/holoeye_slmdisplaysdk.lib CACHE INTERNAL "")
endif()

include(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SLMDISPLAY REQUIRED_VARS SLMDISPLAY_LIBRARY SLMDISPLAY_INCLUDE_DIR)
